### PR TITLE
Should say support 4.x using >=

### PR DESCRIPTION
**Pull request by Eric-Guo**

### CODE REVIEW

**Comment by radar** [comment]
No thanks.

**Comment by Eric-Guo** [comment]
@radar but it will lead install activesupport version 3.2.22 and using it when installing this gems (I'm not using rails 3 now), so is some bug other where?

**Comment by radar** [comment]
@Eric-Guo Please provide steps to reproduce the issue you're seeing.

It's likely it could be fixed by using a `Gemfile`.

**Comment by Eric-Guo** [comment]
@radar No need to using `Gemfile` :smile: 

depend_problem

**Comment by radar** [comment]
Yup.

Please use a `Gemfile` with a specified `activesupport` version in it to prevent this from happening.

```ruby
source "https://rubygems.org"

gem "activesupport", "4.2.4"
gem "redis-activesupport"
```

**Comment by Eric-Guo** [comment]
@radar OK. :+1:

**Pull request closed without merging**
