### PR TITLE
use normalize_key instead of deprecated namespaced_key

### PR DESCRIPTION
**Pull request by dreyks**
`>.<`
Had to make a new PR sadly

the fetch with a block is already fixed in master though

/cc @tubbo

### CODE REVIEW

**Comment by edwardzhou** [comment]
why not merge this PR to eliminate the 'deprecated' warning output

**Comment by numbcoder** [comment]
Merge +1

**Comment by petehamilton** [comment]
Be great to get this merged now Rails 5 is out.

**Comment by iguchi1124** [comment]
:shipit:

**Comment by numbcoder** [comment]
Any problems for this pr?

**Comment by dlackty** [comment]
@tubbo Wondering if there's any chance to cut a gem version release? Seeing tons of deprecation warnings in Rails 5 app with current version of `redis-activesupport`.

**Comment by tubbo** [comment]
@dlackty what version are you running? latest is v5.0.1, and I don't see any deprecation warnings using the latest redis-rails.

**Pull request merged**
