### PR TITLE
add support for connection pooling

### LINKED ISSUE #22: How to inject underlying Redis object, as in the case of connection pooling
Hi there.

When using `redis-rb` directly, I can do something like:
```ruby
redis = ConnectionPool::Wrapper.new(size: 5, timeout: 5) { Redis.new(url: ...) }
```

I've also issued explicit `redis.quit` to keep connection usage low.

Is it possible to do something similar with `redis-store`/`redis-activesupport`?  

Thanks.

### PR DESCRIPTION
**Pull request by substars**
You can either supply size and timeout parameters, or a pool of your own creation.

Fixes #22.

### CODE REVIEW

**Comment by fedenusy** [comment]
+1

**Comment by substars** [comment]
Rebased. Is there anything else I can do to get this merged?

**Comment by radar** [comment]
Find time in the day to give me. That's all.

**Comment by radar** [comment]
Looks good to me!

**Comment by findchris** [comment]
:clap:

**Pull request merged**
