### PR TITLE
Issue #27

### PR DESCRIPTION
**Pull request by lxbrito**
Inconsistent Key marshalling for read_multi/fetch_multi

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Please rebase

**Comment by PikachuEXE** [comment]
This is for #27

**Comment by PikachuEXE** [comment]
Hello? Anyone can merge this?

**Comment by radar** [comment]
I have to ask my assistant first:

```
[13:16:03]  <Radar>	!8ball
[13:16:04]  <helpa>	Outlook good.
```

You're in luck!

**Comment by PikachuEXE** [comment]
What o_0

**Comment by radar** [comment]
My assistant, helpa, informs me of when I can and cannot merge things. The 8ball command is NEVER wrong.

**Pull request merged**
