### PR TITLE
Release v5.0.2

### PR DESCRIPTION
**Pull request by tubbo**
Cut a new gem release for v5.0.2. that uses the current v1.3.0 redis-store.

### CODE REVIEW

**Comment by thibaudgg** [comment]
@tubbo could you please push that one to rubygems? https://rubygems.org/gems/redis-activesupport
Thanks!

**Comment by thibaudgg** [comment]
Tried to use master, but it seems that a bunch of gems needs to be update to make it work.

On my Gemfile:
```
  gem 'redis-actionpack', '~> 5.0.1'
  gem 'redis-activesupport', git: 'https://github.com/redis-store/redis-activesupport.git'
  gem 'redis-rack', '~> 2.0'
  gem 'redis-rails', git: 'https://github.com/redis-store/redis-rails.git'
```

But I still get some dependencies issue:
```
Bundler could not find compatible versions for gem "redis-store":
  In Gemfile:
    redis-actionpack (~> 5.0.1) was resolved to 5.0.1, which depends on
      redis-store (< 1.4.0, >= 1.1.0)

    redis-rails was resolved to 5.0.1, which depends on
      redis-activesupport (~> 5.0.0) was resolved to 5.0.2, which depends on
        redis-store (~> 1.3.0)

    redis-rack (~> 2.0) was resolved to 2.0.0, which depends on
      redis-store (~> 1.2.0)

    redis-rails was resolved to 5.0.1, which depends on
      redis-store (< 1.4, >= 1.2.0)
```

**Comment by tubbo** [comment]
@thibaudgg I just released redis-activesupport v5.0.2 to rubygems.

**Comment by thibaudgg** [comment]
Thanks @tubbo, now it seems that the last thing that prevent us to use redis-rails master with redis-activesupport v5.0.2 is the redis-rack lock on `redis-store ~> 1.2.0`. 

Are you planning to upgrade all gems so they can work together?
Ideally just having `redis-rails ~> 5.0.2` in your Gemfile would be great! 😍 

```
Bundler could not find compatible versions for gem "redis-store":
  In Gemfile:
    redis-actionpack (~> 5.0.1) was resolved to 5.0.1, which depends on
      redis-store (< 1.4.0, >= 1.1.0)

    redis-activesupport (~> 5.0.2) was resolved to 5.0.2, which depends on
      redis-store (~> 1.3.0)

    redis-rack (~> 2.0) was resolved to 2.0.0, which depends on
      redis-store (~> 1.2.0)

    redis-rails was resolved to 5.0.1, which depends on
      redis-store (< 1.4, >= 1.2.0)
```

**Comment by thibaudgg** [comment]
@tubbo great news, thanks!

**Pull request merged**
