### PR TITLE
Fixed #46

### LINKED ISSUE #46: NoMethodError - undefined method `size' for #<Redis::Future:0x007f87b1fa1d48>:
Sorry to bother you.

When I use [jbuilder_cache_multi](https://github.com/joshblour/jbuilder_cache_multi) gem, I encountered the following error.

```
NoMethodError - undefined method `size' for #<Redis::Future:0x007f87b1fa1d48>:
  redis-store (1.1.7) lib/redis/store/marshalling.rb:41:in `unmarshal?'
  redis-store (1.1.7) lib/redis/store/marshalling.rb:33:in `_unmarshal'
  redis-store (1.1.7) lib/redis/store/marshalling.rb:17:in `get'
  redis-store (1.1.7) lib/redis/store/namespace.rb:21:in `block in get'
  redis-store (1.1.7) lib/redis/store/namespace.rb:74:in `namespace'
  redis-store (1.1.7) lib/redis/store/namespace.rb:21:in `get'
  redis-activesupport (4.1.5) lib/active_support/cache/redis_store.rb:230:in `block in read_entry'
  redis-activesupport (4.1.5) lib/active_support/cache/redis_store.rb:212:in `with'
  redis-activesupport (4.1.5) lib/active_support/cache/redis_store.rb:230:in `read_entry'
  activesupport (4.2.4) lib/active_support/cache.rb:558:in `block in find_cached_entry'
  activesupport (4.2.4) lib/active_support/cache.rb:547:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:166:in `instrument'
  activesupport (4.2.4) lib/active_support/cache.rb:547:in `instrument'
  activesupport (4.2.4) lib/active_support/cache.rb:556:in `find_cached_entry'
  activesupport (4.2.4) lib/active_support/cache.rb:293:in `fetch'
  jbuilder (2.3.2) lib/jbuilder/jbuilder_template.rb:35:in `cache!'
  app/views/api/v1/shared/_user.json.jbuilder:7:in `_app_views_api_v__shared__user_json_jbuilder__1877584392314435341_70110396043520'
```

And https://github.com/redis/redis-rb/issues/339

Why the `fetch_multi` method to use `multi` command?
Why not `mset` command?
If it using `mset` command, I think I would not encounter this problem.

### PR DESCRIPTION
**Pull request by tumayun**
Fixed #46

### CODE REVIEW

**Comment by tubbo** [comment]
@tumayun can you give `gem 'redis-activesupport', github: 'redis-store/redis-activesupport'` a shot and see if it fixes your problem?

**Comment by tumayun** [comment]
@tubbo OK, Let me try.

**Comment by tumayun** [comment]
@tubbo not fixed.

**Comment by tubbo** [comment]
@tumayun alright well, go ahead and rebase this branch with 'master' so it's up-to-date and I'll merge it in.

**Comment by tumayun** [comment]
@tubbo Now you can merge it.

**Pull request merged**
