### PR TITLE
Update read-multi-no-keys-v4 with tests

### PR DESCRIPTION
**Pull request by AmirMingaliev**
Hi @tubbo. This PR added changes, which you mentioned in #80. 

Should I also add changes from #74 ?

### CODE REVIEW

**Comment by tubbo** [comment]
@AmirMingaliev Since this is just continuing work on a feature branch, I'll decline my PR and merge this once tests pass. Looks like it has all the changes we were looking for.

**Comment by AmirMingaliev** [comment]
@tubbo What about changes from #74 ? :)

**Comment by tubbo** [comment]
@AmirMingaliev yeah, add those in too. those really should've been part of the same PR in the first place.

**Comment by AmirMingaliev** [comment]
Hi @tubbo. I have added changes from #74 and also from #51. But tests fails on `rbx-19` and `jruby` versions, could you please take a look? 

Also have a question related to `redis-sentinel`. Will it work on `redis-rails 4.0.0` version?

**Comment by tubbo** [comment]
@AmirMingaliev You can go ahead and add `rbx-19mode` to the allowed failures section, or just delete it outright. We don't support rbx 1.9 mode anymore because rbx has EOLed it.

**Comment by tubbo** [comment]
I closed the other PR related to this, we're just going to merge this one so it's all one big change.

**Comment by AmirMingaliev** [comment]
@tubbo done, tests are green now :)

**Comment by AmirMingaliev** [comment]
Hi @tubbo. I believe `redis sentinel` works fine with `redis-rails 4.0.0`. I can prepare the PR, which adds https://github.com/redis-store/redis-rails#usage-with-redis-sentinel documentation to `redis-rails 4.0.0` version. I think that will prevent some misunderstanding. What do you think?

**Comment by AmirMingaliev** [comment]
@tubbo Is there any updates here?

**Comment by AmirMingaliev** [comment]
Hi @tubbo, could you please tell the status of this PR?

**Comment by tubbo** [comment]
sorry @AmirMingaliev, was busy in the real world...yeah I can put that in the v4.1 branch. this also seems like it should work in 4.x so I'm merging. will release a `.pre` version so you can QA it on your own app.

**Comment by tubbo** [comment]
@AmirMingaliev **v4.1.6.pre** has been released on RubyGems

**Comment by AmirMingaliev** [comment]
@tubbo Thank you very much 🎆

**Pull request merged**
