### PR TITLE
Revert "Use SCAN for delete_matched if client and server supports it"

### PR DESCRIPTION
**Pull request by mathieujobin**
This reverts commit 850c0093497dcdeebbcab38eb9fe6c2124c2d7d1.

but keeping the changes done in the test

In my opinion, this must be reverted.
we deployed our service with this and had to be rollback

scan_each takes between 60 seconds and 185 seconds to return depending on the amount of data.
while keys takes 0.13 seconds on average.

### CODE REVIEW

**Comment by jponc** [comment]
+1 for this. Scan slows everything down. Good thing we checked New Relic

**Comment by tubbo** [comment]
Hey sorry for the lack of movement on this. But I wanted to address how the Redis documentation tells us to use SCAN instead of KEYS on very large datasets. If I'm hearing right, you folks are saying that this is the exact opposite? Or is it that you have smaller datasets and it's taking a long time to come back with results?

- T

**Comment by mathieujobin** [comment]
i don't know how large `large` has to be... but we make extensive use of redis and in our case SCAN was an order of magnitude slower than KEYS

> scan_each takes between 60 seconds and 185 seconds to return depending on the amount of data.
while keys takes 0.13 seconds on average.

**Comment by tubbo** [comment]
How large is your dataset @mathieujobin ?

- T

**Comment by tubbo** [comment]
@mathieujobin @jponc This is not the end. :) Please QA this on your own apps and let me know if it fixes anything before I release a version.

**Comment by mathieujobin** [comment]
one of my redis data set is 2.4M

under which both KEYS and SCAN are terribly slow.

I'll be looking at splitting up this data set into multiple unless we find a better solution

**Comment by tubbo** [comment]
@mathieujobin how long does it take `scan_each` to return the full dataset?

**Comment by tubbo** [comment]
this is now in the master branch fwiw, please use a git dependency and let me know if it fixes your issue

**Comment by josephpage** [comment]
Same on my side. SCAN slows everything down 100x.

**Comment by tubbo** [comment]
This has been released in **v5.0.3**.

**Pull request merged**
